### ISSUE TITLE
Document how to build

### ISSUE THREAD

**Issue by PerMildner** [jerinphilip/toy-mlir#8]
It would be really nice if the README.md contained build instructions.

Presumably a person interested in this repo will be new to the MLIR/LLVM and possibly to CMake, so figuring out how to build could be nontrivial.

**Comment by jerinphilip** [comment]
I have pushed https://github.com/jerinphilip/toy-mlir/commit/64689919bfda39eed1ac456942469e2e7d30a436. Let me know if this fills some missing context. The scripts were present prior to this.

The components (MLIR and related) appear to be still evolving and unstable (my quick build attempt on `llvm-project@main` did not succeed). The pinned commit built successfully for me. 

Please allow me to add a disclaimer that I'm not involved with MLIR - this may not even be a recommended way for most people. This is the form I like consuming the content again in - the diff views progressively adding complication, without omitting some details I felt the tutorial did. The standalone-build is a by-product.

**Comment by PerMildner** [comment]
Hello,

Thank you for the quick fix.

I think your changes are more than enough. The missing piece was that the README.md did not mention that there are build scripts in your repo, once I know this I can figure things out.

Thanks again.
